const HashMap = require('./hashmap');

const test = new HashMap(16, 0.75);
test.set('apple', 'red');
test.set('moon', 'silver');
test.set('carrot', 'orange');
test.set('dog', 'brown');
test.set('elephant', 'gray');
test.set('frog', 'green');
test.set('grape', 'purple');
test.set('hat', 'black');
test.set('ice cream', 'white');
test.set('jacket', 'blue');
test.set('kite', 'pink');
test.set('lion', 'golden');
console.log(test.length());
console.log(test.has('apple'));
console.log(test.has('moon'));
console.log(test.has('sun'));
test.set('carrot', 'purple');
console.log(test.length());
test.set('sun', 'yellow');
console.log(test.length());
console.log(test.has('sun'));
test.remove('sun');
console.log(test.has('sun'));
console.log(test.entries());
console.log(test.keys());
console.log(test.values());
console.log(test.get('apple'));
test.clear();
console.log(test.length());
console.log(test.entries());
